SYSTEM:
  NUM_GPUS: 4
  MAX_MEMORY_IN_GB: 64

DATASET:
  CUSTOMIZED_DATASETS:
    - raw_data/wikipedia
    - raw_data/bookcorpus

PRETRAIN:
  NUM_STEPS: 23000

TOKENIZER:
  NAME_OR_PATH: bert-large-uncased
